version: "3.8"

services:
  shopware:
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - "4488:80"
    environment:
      XDEBUG_ENABLED: 0
    volumes:
      - shopware_data:/var/www/html
      - ./custom/plugins/LodinPayment:/var/www/html/custom/plugins/LodinPayment
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: shopware-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  shopware_data:
  mysql_data:
